# Generated by Django 5.0.4 on 2024-06-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockalert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_info',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
