# Generated by Django 5.0.4 on 2024-06-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockalert', '0002_stock_info_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_info',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
