# Generated by Django 5.0.4 on 2024-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockalert', '0003_stock_info_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_info',
            name='price',
            field=models.FloatField(),
        ),
    ]
