# Generated by Django 5.0.4 on 2024-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockalert', '0004_alter_stock_info_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_info',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
